// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh3BsXamIAbHJ_54eD10PVW23eFkDC2Vk',
    appId: '1:50173698522:web:4ef38ff66c64fade9f60e3',
    messagingSenderId: '50173698522',
    projectId: 'mobsec-b45c7',
    authDomain: 'mobsec-b45c7.firebaseapp.com',
    storageBucket: 'mobsec-b45c7.appspot.com',
    measurementId: 'G-7BB3LNSRNE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEvZnH-V-kwDgp1D7eVD-mgxvLh0HPyo0',
    appId: '1:50173698522:android:0669613f7c2d51f39f60e3',
    messagingSenderId: '50173698522',
    projectId: 'mobsec-b45c7',
    storageBucket: 'mobsec-b45c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB80IIz7zTeacB67WawblNMSrDRLzYqwzI',
    appId: '1:50173698522:ios:96a1336e473a91169f60e3',
    messagingSenderId: '50173698522',
    projectId: 'mobsec-b45c7',
    storageBucket: 'mobsec-b45c7.appspot.com',
    iosClientId: '50173698522-6ipnu270jbi65vlb6cli7hprarj0v3ep.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobsec',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB80IIz7zTeacB67WawblNMSrDRLzYqwzI',
    appId: '1:50173698522:ios:945cfc98f94f4b909f60e3',
    messagingSenderId: '50173698522',
    projectId: 'mobsec-b45c7',
    storageBucket: 'mobsec-b45c7.appspot.com',
    iosClientId: '50173698522-71p8kqhs0ehnb9bjt0pfv4b3lubng937.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobsec.RunnerTests',
  );
}
